### ISSUE TITLE
Callback option and NPM

### ISSUE THREAD

**Issue by sergey-pimenov** [kimulaco/vanilla-smoothie#1]
Hi!

I tried about 10 similar libraries, but yours the most convenient and have opportunities which are not in others (even very popular solutions). It will be great if you add to lib callback. Like:

`smoothScroll.scrollTo(768, 600, document.body, callback);`

It's gonna be really cool!

In addition, it would be great if it will be possible to install the library through npm and then export to JS.

**Comment by kimulaco** [comment]
Sorry for being so late.

The package name is duplicated, so it has been changed to support both the browser and npm. You can also use the Callback function.

```js
import vanillaSmoothie from 'vanilla-smoothie';

vanillaSmoothie.scrollTo('#anchor-01', 500, document.body, () => {
    console.log('Callback!!');
});
```

This task will be closed once.
